In [3]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from textblob import TextBlob   #to process natural language

#load Data
data = pd.read_csv("Sentiment_Analysis .csv")

In [5]:
!pip install textblob

Collecting textblob
  Downloading textblob-0.19.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: nltk>=3.9 in c:\users\sahup\anaconda3\lib\site-packages (from textblob) (3.9.1)
Requirement already satisfied: click in c:\users\sahup\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (8.1.8)
Requirement already satisfied: joblib in c:\users\sahup\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\sahup\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\sahup\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (4.67.1)
Requirement already satisfied: colorama in c:\users\sahup\anaconda3\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)
Downloading textblob-0.19.0-py3-none-any.whl (624 kB)
   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/624.3 kB ? eta -:--:--
   ---------------------------------------- 624.3/624.3 kB 2.0 MB/s eta 0:00:00
Installing collected packages: textblob
Successfully installed textblob-0.19.0

In [4]:
data.head(10)

                                           Sentences
0  The product's exceptional quality and performa...
1  Poor customer support and the product's subpar...
2  The service met standard requirements without ...
3  Outstanding customer service accompanied the p...
4  The product's failure to meet basic requiremen...
5  The service provided met basic needs without n...
6  Remarkable product quality and performance exc...
7  Poor customer service and a faulty product led...
8  The service provided was average, meeting mini...
9  The purchase proved delightful, with the produ...

In [5]:
#Define the sentiment Analysis
def get_sentiment(text):
    analysis = TextBlob(text)
    if analysis.sentiment.polarity > 0:
        return "Positive"
    elif analysis.sentiment.polarity < 0:
        return "Negative"
    else:
        return "Neutral"
#Apply sentiment
data['Sentiment'] = data['Sentences'].apply(get_sentiment)

In [6]:
data.head(20)

                                            Sentences Sentiment
0   The product's exceptional quality and performa...  Positive
1   Poor customer support and the product's subpar...  Negative
2   The service met standard requirements without ...  Positive
3   Outstanding customer service accompanied the p...  Positive
4   The product's failure to meet basic requiremen...  Negative
5   The service provided met basic needs without n...  Positive
6   Remarkable product quality and performance exc...  Positive
7   Poor customer service and a faulty product led...  Negative
8   The service provided was average, meeting mini...  Negative
9   The purchase proved delightful, with the produ...  Positive
10  The product's performance fell significantly s...   Neutral
11  The service provided was acceptable, meeting b...  Positive
12  Impeccable product quality and performance far...  Positive
13  Dreadful customer support coupled with a defec...  Negative
14  The service rendered met basic requirements wi...  Positive
15  Exceptional customer service enhanced the over...  Positive
16  Severe product shortcomings led to considerabl...  Negative
17  The service was standard, meeting basic needs ...  Negative
18  The purchase proved delightful, offering a sup...  Positive
19  Disappointing product quality and poor custome...  Negative

In [7]:
data.to_csv("Feedbak_File.csv",index=False)